name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install -g pnpm
        pnpm install
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
    
    - name: Build frontend
      working-directory: ./frontend
      run: pnpm build
      
    - name: Run backend tests
      working-directory: ./backend
      run: echo "Tests would run here"
